Feature/header
BFF-Unlimited/bff-unlimited pull request #22
Opened 2022-09-27 13:30 UTC by sveroude

2022-09-27 14:29 UTC, devbyray requested changes
Ik heb 2 comments 😉

2022-09-27 14:29 UTC, devbyray commented on Client/src/stores/user.ts
> +  user: ref<ActiveUser>(),
Wat is de reden dat je er niks in stopt? Met die class erin krijg je nooit verrassingen dat een property `undefined` is 😉

2022-09-27 14:29 UTC, devbyray commented on Client/nuxt.config.ts
> -  dirs: [
Waarom is dit verwijderd? Dit zorgt ervoor dat alle composables zonder import in een component gebruikt kan worden.

2022-09-28 09:57 UTC, rahmatsyamsuddin requested changes

2022-09-28 09:57 UTC, rahmatsyamsuddin commented on Client/src/pages/index.vue
>      <template #sidebar><AppSidebar :menu="sidebarStore.navigation" /></template>
TheAppSidebar. er is maar 1 sidebar

2022-09-28 09:57 UTC, rahmatsyamsuddin commented on Client/src/layouts/default.css
>      'header header '
extra space weghalen

2022-09-28 09:57 UTC, rahmatsyamsuddin commented on Client/src/models/user.model.ts
>  export interface ActiveUser {
Wat is het verschil tussen de ActiveUser vs ActiveUserModel?

2022-09-28 09:57 UTC, rahmatsyamsuddin commented on Client/src/models/user.model.ts
>  export interface ActiveUser {
nvm, ik snap het nu.

2022-09-28 09:57 UTC, rahmatsyamsuddin commented on Client/src/models/user.model.ts
> +  constructor(input: any) {
is de any type, dan niet gewoon een ActiveUser?

2022-10-03 11:56 UTC, rahmatsyamsuddin approved these changes

2022-10-03 11:59 UTC, merged